/*PikaCRM database version 1*/

CREATE TABLE "BuyItem" ("O_id" INTEGER NOT NULL , "B_id" INTEGER NOT NULL , "M_id" INTEGER NOT NULL , "B_price" FLOAT NOT NULL , "B_number" INTEGER NOT NULL , PRIMARY KEY ("O_id", "B_id"));

CREATE TABLE "Contact" ("Co_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "C_id" INTEGER, "Co_name" CHAR NOT NULL , "Co_phone" CHAR, "Co_address" CHAR, "Co_email" CHAR, "Co_ctime" DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP, "Co_profile" BLOB, "Co_card" BLOB, "Co_1" BLOB, "Co_2" BLOB, "Co_3" BLOB);

CREATE TABLE "Customer" ("C_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "C_title" CHAR NOT NULL , "C_phone" CHAR, "C_address" CHAR, "C_email" CHAR, "C_website" CHAR, "C_ccount" INTEGER NOT NULL  DEFAULT 0, "C_ctime" DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP, "C_1" BLOB, "C_2" BLOB, "C_3" BLOB);

CREATE TABLE "Event" ("E_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "C_id" INTEGER NOT NULL , "E_ask" TEXT NOT NULL , "E_status" CHAR, "E_ctime" DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP, "E_note" TEXT);

CREATE TABLE "Field" ("F_table" CHAR NOT NULL , "F_idname" CHAR NOT NULL , "F_name" CHAR NOT NULL , PRIMARY KEY ("F_table", "F_idname"));

CREATE TABLE "LinkContact" ("O_id" INTEGER NOT NULL , "Co_id" INTEGER NOT NULL , PRIMARY KEY ("O_id", "Co_id"));

CREATE TABLE "Merchandise" ("M_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "M_name" CHAR NOT NULL , "M_price" INTEGER, "M_1" BLOB, "M_2" BLOB, "M_3" BLOB);

CREATE TABLE "Order" ("O_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "C_id" INTEGER NOT NULL , "O_ship_add" CHAR, "O_bill_add" CHAR, "O_date" DATETIME, "O_ctime" DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP, "O_mtime" DATETIME, "O_note" TEXT);

CREATE TABLE "System" ("user" CHAR NOT NULL , "ctime" DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP, "ap_ver" CHAR NOT NULL , "sqlite_ver" CHAR NOT NULL , "db_ver" CHAR NOT NULL );

CREATE TABLE "Unlimited" ("U_id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "U_name" CHAR NOT NULL );

CREATE TABLE "UserCustomize" ("U_id" INTEGER NOT NULL , "C_id" INTEGER NOT NULL , "Us_content" BLOB NOT NULL , PRIMARY KEY ("U_id", "C_id"));
